// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaWqFA8RJLtCvZ94iZcYGrCtu2vaNB73Q',
    appId: '1:472990299269:web:12fc0b621a295db200a5ec',
    messagingSenderId: '472990299269',
    projectId: 'the-book-club-26855',
    authDomain: 'the-book-club-26855.firebaseapp.com',
    storageBucket: 'the-book-club-26855.firebasestorage.app',
    measurementId: 'G-R96KDD3FWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe6FWzRCB8bI4i7LSwzVi-B-O3XwBtXh0',
    appId: '1:472990299269:android:6ff07e37055c970000a5ec',
    messagingSenderId: '472990299269',
    projectId: 'the-book-club-26855',
    storageBucket: 'the-book-club-26855.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOgumTTBPejHeDUlyuBnH9uVCQ9cyiIQ',
    appId: '1:472990299269:ios:1f384ff181ecdd3800a5ec',
    messagingSenderId: '472990299269',
    projectId: 'the-book-club-26855',
    storageBucket: 'the-book-club-26855.firebasestorage.app',
    iosBundleId: 'com.example.theBookClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLOgumTTBPejHeDUlyuBnH9uVCQ9cyiIQ',
    appId: '1:472990299269:ios:1f384ff181ecdd3800a5ec',
    messagingSenderId: '472990299269',
    projectId: 'the-book-club-26855',
    storageBucket: 'the-book-club-26855.firebasestorage.app',
    iosBundleId: 'com.example.theBookClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaWqFA8RJLtCvZ94iZcYGrCtu2vaNB73Q',
    appId: '1:472990299269:web:4226b79917b84c3d00a5ec',
    messagingSenderId: '472990299269',
    projectId: 'the-book-club-26855',
    authDomain: 'the-book-club-26855.firebaseapp.com',
    storageBucket: 'the-book-club-26855.firebasestorage.app',
    measurementId: 'G-2DHEJPPZN6',
  );
}
