// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFWgKrcjJjmFNo_lHr4oyzwZxD4izxm8',
    appId: '1:933149243820:web:48dd6e5987ec21189c6209',
    messagingSenderId: '933149243820',
    projectId: 'the-book-club-19c4d',
    authDomain: 'the-book-club-19c4d.firebaseapp.com',
    storageBucket: 'the-book-club-19c4d.firebasestorage.app',
    measurementId: 'G-962K2N6S4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChDsxvwYqZKilf-BT0etHPqfMX4w01MQc',
    appId: '1:933149243820:android:75d3d80c9258929c9c6209',
    messagingSenderId: '933149243820',
    projectId: 'the-book-club-19c4d',
    storageBucket: 'the-book-club-19c4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4BxEtx5Tk8kLLq7CbZy43guRJZmYg9gE',
    appId: '1:933149243820:ios:70288e9d7e1340689c6209',
    messagingSenderId: '933149243820',
    projectId: 'the-book-club-19c4d',
    storageBucket: 'the-book-club-19c4d.firebasestorage.app',
    iosBundleId: 'com.example.bookRecReviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4BxEtx5Tk8kLLq7CbZy43guRJZmYg9gE',
    appId: '1:933149243820:ios:70288e9d7e1340689c6209',
    messagingSenderId: '933149243820',
    projectId: 'the-book-club-19c4d',
    storageBucket: 'the-book-club-19c4d.firebasestorage.app',
    iosBundleId: 'com.example.bookRecReviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOFWgKrcjJjmFNo_lHr4oyzwZxD4izxm8',
    appId: '1:933149243820:web:96ff7962649b2c6a9c6209',
    messagingSenderId: '933149243820',
    projectId: 'the-book-club-19c4d',
    authDomain: 'the-book-club-19c4d.firebaseapp.com',
    storageBucket: 'the-book-club-19c4d.firebasestorage.app',
    measurementId: 'G-6FJWHZ4DKZ',
  );
}
